# Generated by Django 5.1.4 on 2025-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('state', models.CharField(max_length=255, verbose_name='المحافظة')),
                ('country', models.CharField(max_length=255, verbose_name='الدول')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'المناطق',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='اسم الفندق')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='hotels/images/')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='وصف الفندق')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
            ],
            options={
                'verbose_name': 'فندق',
                'verbose_name_plural': 'فنادق',
            },
        ),
        migrations.CreateModel(
            name='HotelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='اسمك')),
                ('email', models.EmailField(max_length=254, verbose_name='بريدك الإلكتروني')),
                ('role', models.CharField(max_length=50, verbose_name='دورك في العمل')),
                ('hotel_name', models.CharField(max_length=255, verbose_name='اسم الفندق')),
                ('description', models.TextField(verbose_name='وصف الفندق')),
                ('profile_picture', models.ImageField(upload_to='hotel_requests/images/', verbose_name='صورة الفندق الرئيسية')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('city_name', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان التفصيلي')),
                ('country_code', models.CharField(max_length=5, verbose_name='رمز الدولة')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('additional_images', models.JSONField(blank=True, default=list, verbose_name='صور إضافية')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تمت الموافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
            ],
            options={
                'verbose_name': 'طلب إضافة فندق',
                'verbose_name_plural': 'طلبات إضافة الفنادق',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='hotels/images/', verbose_name='مسار الصورة')),
                ('image_url', models.CharField(blank=True, max_length=3000, null=True, verbose_name='مسار الصورة على الانترنت')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'صور',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'الموقع',
                'verbose_name_plural': 'المواقع',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('phone_number', models.CharField(max_length=10, verbose_name='رقم الهاتف')),
                ('country_code', models.CharField(max_length=5, verbose_name='رمز الدوله')),
            ],
            options={
                'verbose_name': 'رقم هاتف',
                'verbose_name_plural': 'أرقام الهواتف',
            },
        ),
    ]
