# Generated by Django 5.0.7 on 2024-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0002_alter_image_options_city_slug_hotel_slug_image_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
