# Generated by Django 5.0.7 on 2024-11-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0003_alter_image_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
