# Generated by Django 5.1.3 on 2024-12-10 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0003_alter_city_name_alter_hotel_name_alter_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='manager',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'hotel_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدير الفندق'),
        ),
    ]
