# Generated by Django 5.1.3 on 2024-12-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0004_hotel_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='HotelManagement.hotel', verbose_name='الفندق'),
            preserve_default=False,
        ),
    ]
