# Generated by Django 5.0.7 on 2024-11-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hotel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HotelManagement.hotel', verbose_name='فندق'),
            preserve_default=False,
        ),
    ]
