# Generated by Django 5.1.4 on 2025-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('currency_name', models.CharField(max_length=50, verbose_name='اسم العملة')),
                ('currency_symbol', models.CharField(max_length=10, verbose_name='رمز العملة')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['currency_name'],
            },
        ),
        migrations.CreateModel(
            name='HotelPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('iban', models.CharField(max_length=50, verbose_name='رقم الآيبان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='تعليمات الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طريقة دفع الفندق',
                'verbose_name_plural': 'طرق دفع الفندق',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[(0, 'قيد الانتظار'), (1, 'مكتمل'), (2, 'فشل'), (3, 'مسترد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('payment_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الفرعي')),
                ('payment_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('payment_totalamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('payment_currency', models.CharField(default='USD', max_length=25, verbose_name='العملة')),
                ('payment_note', models.TextField(blank=True, max_length=300, null=True, verbose_name='ملاحظات')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('e_pay', 'دفع إلكتروني')], default='cash', max_length=20, verbose_name='نوع الدفع')),
            ],
            options={
                'verbose_name': 'فاتورة دفع',
                'verbose_name_plural': 'فواتير الدفع',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100, verbose_name='اسم طريقة الدفع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_logos/', verbose_name='شعار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
    ]
