# Generated by Django 5.1.3 on 2024-12-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('currency_name', models.CharField(max_length=50, verbose_name='اسم العملة')),
                ('currency_symbol', models.CharField(max_length=10, verbose_name='رمز العملة')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['currency_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('payment_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الفرعي')),
                ('payment_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('payment_totalamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('payment_note', models.TextField(blank=True, max_length=300, null=True, verbose_name='ملاحظات')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('e_pay', 'دفع إلكتروني')], default='cash', max_length=20, verbose_name='نوع الدفع')),
            ],
            options={
                'verbose_name': 'فاتورة دفع',
                'verbose_name_plural': 'فواتير الدفع',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('method_name', models.CharField(max_length=50, verbose_name='اسم طريقة الدفع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='الشعار')),
                ('activate_state', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('country', models.CharField(max_length=50, verbose_name='الدولة')),
                ('transfer_number', models.CharField(blank=True, max_length=66, null=True, verbose_name='رقم التحويل')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['-activate_state', 'method_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('payment_status_name', models.CharField(max_length=50, verbose_name='اسم حالة الدفع')),
                ('status_code', models.IntegerField(verbose_name='رمز الحالة')),
            ],
            options={
                'verbose_name': 'حالة الدفع',
                'verbose_name_plural': 'حالات الدفع',
                'ordering': ['status_code'],
            },
        ),
    ]
