# Generated by Django 5.1.3 on 2024-12-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_add_staff',
            field=models.BooleanField(default=False, verbose_name='إضافة موظفين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_cancel_bookings',
            field=models.BooleanField(default=False, verbose_name='إلغاء الحجوزات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_confirm_bookings',
            field=models.BooleanField(default=False, verbose_name='تأكيد الحجوزات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_create_discounts',
            field=models.BooleanField(default=False, verbose_name='إنشاء خصومات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_discounts',
            field=models.BooleanField(default=False, verbose_name='حذف الخصومات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_reviews',
            field=models.BooleanField(default=False, verbose_name='حذف التقييمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_edit_staff',
            field=models.BooleanField(default=False, verbose_name='تعديل بيانات الموظفين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_export_reports',
            field=models.BooleanField(default=False, verbose_name='تصدير التقارير'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_hotel_settings',
            field=models.BooleanField(default=False, verbose_name='إدارة إعدادات الفندق'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_room_availability',
            field=models.BooleanField(default=False, verbose_name='إدارة توفر الغرف'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_room_prices',
            field=models.BooleanField(default=False, verbose_name='إدارة أسعار الغرف'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_staff_permissions',
            field=models.BooleanField(default=False, verbose_name='إدارة صلاحيات الموظفين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_modify_booking_prices',
            field=models.BooleanField(default=False, verbose_name='تعديل أسعار الحجوزات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_modify_discounts',
            field=models.BooleanField(default=False, verbose_name='تعديل الخصومات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_respond_to_reviews',
            field=models.BooleanField(default=False, verbose_name='الرد على التقييمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_financial_reports',
            field=models.BooleanField(default=False, verbose_name='عرض التقارير المالية'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='عرض التقارير'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_staff',
            field=models.BooleanField(default=False, verbose_name='عرض الموظفين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_statistics',
            field=models.BooleanField(default=False, verbose_name='عرض الإحصائيات'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='can_edit_hotel',
            field=models.BooleanField(default=False, verbose_name='تعديل الفندق'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='can_view_hotel',
            field=models.BooleanField(default=False, verbose_name='عرض الفندق'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
    ]
