# Generated by Django 5.1.3 on 2024-11-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=True, upload_to='user/%y/%m/%d'),
        ),
    ]
