# Generated by Django 3.2.10 on 2024-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelaccountrequest',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='hotelaccountrequest',
            name='updated_user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to='user/%y/%m/%d'),
        ),
    ]
