# Generated by Django 5.0.7 on 2024-11-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=False, upload_to='user/%y/%m/%d'),
        ),
    ]
