# Generated by Django 5.1.3 on 2024-12-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permissiongroup_can_add_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='can_manage_bookings',
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='can_manage_reviews',
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_add_bookings',
            field=models.BooleanField(default=False, verbose_name='إضافة حجوزات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_add_locations',
            field=models.BooleanField(default=False, verbose_name='إضافة مواقع'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_add_offers',
            field=models.BooleanField(default=False, verbose_name='إضافة عروض'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_add_reviews',
            field=models.BooleanField(default=False, verbose_name='إضافة تقييمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_add_services',
            field=models.BooleanField(default=False, verbose_name='إضافة خدمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_add_users',
            field=models.BooleanField(default=False, verbose_name='إضافة مستخدمين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_bookings',
            field=models.BooleanField(default=False, verbose_name='حذف الحجوزات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_locations',
            field=models.BooleanField(default=False, verbose_name='حذف المواقع'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_offers',
            field=models.BooleanField(default=False, verbose_name='حذف العروض'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_services',
            field=models.BooleanField(default=False, verbose_name='حذف الخدمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_staff',
            field=models.BooleanField(default=False, verbose_name='حذف الموظفين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_users',
            field=models.BooleanField(default=False, verbose_name='حذف المستخدمين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_edit_bookings',
            field=models.BooleanField(default=False, verbose_name='تعديل الحجوزات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_edit_locations',
            field=models.BooleanField(default=False, verbose_name='تعديل المواقع'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_edit_offers',
            field=models.BooleanField(default=False, verbose_name='تعديل العروض'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_edit_reviews',
            field=models.BooleanField(default=False, verbose_name='تعديل التقييمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_edit_services',
            field=models.BooleanField(default=False, verbose_name='تعديل الخدمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_edit_users',
            field=models.BooleanField(default=False, verbose_name='تعديل المستخدمين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_cities',
            field=models.BooleanField(default=False, verbose_name='إدارة المدن'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_permissions',
            field=models.BooleanField(default=False, verbose_name='إدارة الصلاحيات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_service_prices',
            field=models.BooleanField(default=False, verbose_name='إدارة أسعار الخدمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_process_payments',
            field=models.BooleanField(default=False, verbose_name='معالجة المدفوعات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_refund_payments',
            field=models.BooleanField(default=False, verbose_name='استرداد المدفوعات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_admin',
            field=models.BooleanField(default=False, verbose_name='الوصول للوحة التحكم'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_booking_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول الحجوزات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_city_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول المدن'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_hotel_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول الفنادق'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_image_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول الصور'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_location_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول المواقع'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_locations',
            field=models.BooleanField(default=False, verbose_name='عرض المواقع'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_offer_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول العروض'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_payment_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول المدفوعات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_payment_reports',
            field=models.BooleanField(default=False, verbose_name='عرض تقارير المدفوعات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_payments',
            field=models.BooleanField(default=False, verbose_name='عرض المدفوعات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_permissions',
            field=models.BooleanField(default=False, verbose_name='عرض الصلاحيات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_review_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول التقييمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_room_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول الغرف'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_service_model',
            field=models.BooleanField(default=True, verbose_name='عرض جدول الخدمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_services',
            field=models.BooleanField(default=False, verbose_name='عرض الخدمات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_users',
            field=models.BooleanField(default=False, verbose_name='عرض المستخدمين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='مدير النظام'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
