# Generated by Django 5.1.3 on 2024-12-18 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0002_initial'),
        ('users', '0003_remove_permissiongroup_can_manage_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_assign_permissions',
            field=models.BooleanField(default=False, verbose_name='تعيين صلاحيات للموظفين'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_create_permission_groups',
            field=models.BooleanField(default=False, verbose_name='إنشاء مجموعات صلاحيات'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='is_hotel_manager',
            field=models.BooleanField(default=False, verbose_name='مدير الفندق'),
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelManagement.hotel', verbose_name='الفندق')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permissiongroup', verbose_name='مجموعة الصلاحيات')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المستهدف')),
            ],
            options={
                'verbose_name': 'طلب صلاحيات',
                'verbose_name_plural': 'طلبات الصلاحيات',
                'ordering': ['-created_at'],
            },
        ),
    ]
