# Generated by Django 5.1.3 on 2024-11-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_image'),
        ('users', '0003_auto_20241127_2054'),
    ]

    operations = [
    ]
