# Generated by Django 5.1.3 on 2024-12-18 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0002_initial'),
        ('users', '0004_permissiongroup_can_assign_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='الفندق الذي يعمل به الموظف', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelManagement.hotel', verbose_name='الفندق'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('manager', 'مدير الفندق'), ('receptionist', 'موظف استقبال'), ('booking_agent', 'مسؤول حجوزات'), ('housekeeping', 'مشرف نظافة'), ('maintenance', 'مسؤول صيانة'), ('accountant', 'محاسب')], max_length=20, null=True, verbose_name='نوع الموظف'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('hotel_manager', 'مدير فندق'), ('receptionist', 'موظف استقبال'), ('booking_agent', 'مسؤول حجوزات'), ('housekeeping', 'مشرف نظافة'), ('maintenance', 'مسؤول صيانة'), ('accountant', 'محاسب'), ('customer', 'عميل')], default='customer', help_text='نوع حساب المستخدم في النظام', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
