# Generated by Django 5.1.3 on 2024-11-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20241128_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to='user/%y/%m/%d'),
        ),
    ]
