# Generated by Django 5.1.3 on 2024-12-18 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0002_initial'),
        ('users', '0005_customuser_hotel_permissiongroup_staff_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب صلاحية', 'verbose_name_plural': 'طلبات الصلاحيات'},
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='permission_group',
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='requested_permissions',
            field=models.TextField(default=1, help_text='وصف للصلاحيات المطلوبة', verbose_name='الصلاحيات المطلوبة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='HotelManagement.hotel', verbose_name='الفندق'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف'),
        ),
    ]
