# Generated by Django 5.1.3 on 2024-12-02 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_hotelaccountrequest_admin_notes_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelaccountrequest',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelaccountrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='hotelaccountrequest',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='hotelaccountrequest',
            name='updated_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='admin_notes',
            field=models.TextField(blank=True, default=None, verbose_name='ملاحظات المسؤول'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='business_license_number',
            field=models.CharField(max_length=100, verbose_name='رقم الرخصة التجارية'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='document_path',
            field=models.FileField(upload_to='hotel_documents/', verbose_name='مسار مستند الفندق'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='hotel_description',
            field=models.TextField(verbose_name='وصف الفندق'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='hotel_name',
            field=models.CharField(max_length=255, verbose_name='اسم الفندق'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='اسم المالك'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='verify_number',
            field=models.CharField(max_length=50, verbose_name='رقم التحقق'),
        ),
    ]
