# Generated by Django 5.1.3 on 2024-12-02 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_hotelaccountrequest_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='created_by',
            field=models.OneToOneField(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى'),
        ),
        migrations.AlterField(
            model_name='hotelaccountrequest',
            name='updated_by',
            field=models.OneToOneField(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل'),
        ),
    ]
