# Generated by Django 5.1.3 on 2024-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_hotelaccountrequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelaccountrequest',
            name='password',
            field=models.CharField(default=2, max_length=255, verbose_name='كلمه السر '),
            preserve_default=False,
        ),
    ]
