# Generated by Django 5.1.3 on 2024-12-02 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_hotelaccountrequest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelaccountrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
