# Generated by Django 5.1.3 on 2024-12-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_hotelaccountrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelaccountrequest',
            name='user',
        ),
    ]
