# Generated by Django 5.1.3 on 2024-12-18 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('available_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الغرف المتوفرة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'توفر الغرف',
                'verbose_name_plural': 'توفر الغرف',
                'ordering': ['-date', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='الصورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
            ],
            options={
                'verbose_name': 'صورة الغرفة',
                'verbose_name_plural': 'صور الغرف',
                'ordering': ['-is_main', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('date_from', models.DateField(verbose_name='تاريخ البدء')),
                ('date_to', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='عرض خاص')),
            ],
            options={
                'verbose_name': 'سعر الغرفة',
                'verbose_name_plural': 'أسعار الغرف',
                'ordering': ['-date_from', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=50, verbose_name='رمز الحالة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحالة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الحالة')),
                ('is_available', models.BooleanField(default=True, help_text='هل يمكن حجز الغرف في هذه الحالة؟', verbose_name='متاح للحجز')),
            ],
            options={
                'verbose_name': 'حالة الغرفة',
                'verbose_name_plural': 'حالات الغرف',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع الغرفة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('default_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='السعة الافتراضية')),
                ('max_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='السعة القصوى')),
                ('beds_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الأسرة')),
                ('rooms_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الغرف')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='السعر الافتراضي للغرفة في الليلة الواحدة', max_digits=10, verbose_name='السعر الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للحجز')),
            ],
            options={
                'verbose_name': 'نوع الغرفة',
                'verbose_name_plural': 'أنواع الغرف',
                'ordering': ['category', 'name'],
            },
        ),
    ]
