# Generated by Django 5.0.7 on 2024-12-18 07:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HotelManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف التصنيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=50, verbose_name='رمز الحالة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحالة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الحالة')),
                ('is_available', models.BooleanField(default=True, help_text='هل يمكن حجز الغرف في هذه الحالة؟', verbose_name='متاح للحجز')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_statuses', to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'verbose_name': 'حالة الغرفة',
                'verbose_name_plural': 'حالات الغرف',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع الغرفة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('default_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='السعة الافتراضية')),
                ('max_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='السعة القصوى')),
                ('beds_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الأسرة')),
                ('rooms_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الغرف')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='السعر الافتراضي للغرفة في الليلة الواحدة', max_digits=10, verbose_name='السعر الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للحجز')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='rooms.category', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'verbose_name': 'نوع الغرفة',
                'verbose_name_plural': 'أنواع الغرف',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('date_from', models.DateField(verbose_name='تاريخ البدء')),
                ('date_to', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='عرض خاص')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_prices', to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rooms.roomtype', verbose_name='نوع الغرفة')),
            ],
            options={
                'verbose_name': 'سعر الغرفة',
                'verbose_name_plural': 'أسعار الغرف',
                'ordering': ['-date_from', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='الصورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomtype', verbose_name='نوع الغرفة')),
            ],
            options={
                'verbose_name': 'صورة الغرفة',
                'verbose_name_plural': 'صور الغرف',
                'ordering': ['-is_main', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('available_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الغرف المتوفرة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_availabilities', to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rooms.roomstatus', verbose_name='حالة الغرفة')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rooms.roomtype', verbose_name='نوع الغرفة')),
            ],
            options={
                'verbose_name': 'توفر الغرف',
                'verbose_name_plural': 'توفر الغرف',
                'ordering': ['-date', 'room_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_hotel_category'),
        ),
        migrations.AddConstraint(
            model_name='roomstatus',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='unique_hotel_status_code'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(check=models.Q(('max_capacity__gte', models.F('default_capacity'))), name='max_capacity_gte_default'),
        ),
        migrations.AddConstraint(
            model_name='roomprice',
            constraint=models.CheckConstraint(check=models.Q(('date_to__gt', models.F('date_from'))), name='valid_price_date_range'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_type', 'date'), name='unique_room_availability'),
        ),
    ]
