# Generated by Django 5.1.3 on 2024-12-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(default=None, upload_to='rooms/img/%y/%m/%d', verbose_name='رابط الصورة'),
        ),
    ]
