# Generated by Django 5.0.7 on 2025-01-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('offer_name', models.CharField(max_length=100, verbose_name='اسم العرض')),
                ('offer_description', models.TextField(verbose_name='وصف العرض')),
                ('offer_start_date', models.DateField(verbose_name='تاريخ بداية العرض')),
                ('offer_end_date', models.DateField(verbose_name='تاريخ نهاية العرض')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'db_table': 'service_offers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(default='Default Name', max_length=255, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='وصف الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('additional_fee', models.FloatField(blank=True, null=True, verbose_name='القيمة المضافه')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
    ]
