# Generated by Django 5.1.4 on 2025-01-16 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العرض')),
                ('description', models.TextField(help_text='اكتب تفاصيل العرض وشروطه', verbose_name='وصف العرض')),
                ('start_date', models.DateField(help_text='متى يبدأ العرض؟', verbose_name='تاريخ بداية العرض')),
                ('end_date', models.DateField(help_text='متى ينتهي العرض؟', verbose_name='تاريخ نهاية العرض')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='نسبة الخصم (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم')),
                ('is_active', models.BooleanField(default=True, help_text='هل العرض متاح حالياً؟', verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'نجمة واحدة'), (2, '2 نجوم'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], default=5, help_text='تقييم من 1 إلى 5 نجوم', verbose_name='التقييم')),
                ('review', models.TextField(help_text='اكتب رأيك عن تجربتك في الفندق', verbose_name='التعليق')),
                ('status', models.BooleanField(default=True, help_text='هل المراجعة مرئية للجميع؟', verbose_name='نشط')),
                ('has_reservation', models.BooleanField(default=False, help_text='هل قام المستخدم بالحجز في الفندق؟', verbose_name='لديه حجز')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
