# Generated by Django 5.1.3 on 2024-12-12 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '__first__'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=100, verbose_name='اسم العرض')),
                ('offer_description', models.TextField(verbose_name='وصف العرض')),
                ('offer_start_date', models.DateField(verbose_name='تاريخ بداية العرض')),
                ('offer_end_date', models.DateField(verbose_name='تاريخ نهاية العرض')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'db_table': 'offers',
            },
        ),
    ]
