# Generated by Django 5.1.3 on 2024-12-12 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HotelManagement', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('guest_name', models.CharField(max_length=255, verbose_name='اسم النزيل')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('guest_address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('guest_nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجنسية')),
                ('guest_dob', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('guest_id_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الهوية')),
                ('guest_id_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهوية')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='طلبات خاصة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='HotelManagement.hotel', verbose_name='الفندق')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'verbose_name': 'نزيل',
                'verbose_name_plural': 'النزلاء',
                'db_table': 'guests',
            },
        ),
    ]
