# Generated by Django 5.0.7 on 2024-12-13 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0001_initial'),
        ('bookings', '0001_initial'),
        ('rooms', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'حجز', 'verbose_name_plural': 'حجوزات'},
        ),
        migrations.AlterModelOptions(
            name='bookingdetail',
            options={'verbose_name': 'تفصيل الحجز', 'verbose_name_plural': 'تفاصيل الحجز'},
        ),
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'verbose_name': 'حالة الحجز', 'verbose_name_plural': 'حالات الحجز'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'ضيف', 'verbose_name_plural': 'الضيوف'},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='idCard_number',
        ),
        migrations.AddField(
            model_name='guest',
            name='id_card_number',
            field=models.CharField(default=1, max_length=30, verbose_name='ID Card Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بداية الحجز'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='rooms.roomtype', verbose_name='الغرفة'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details_bookings', to='bookings.booking', verbose_name='الحجز'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details_hotels', to='HotelManagement.hotel', verbose_name='الفندق'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details_sercives', to='services.service', verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_accounts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_bookings', to='bookings.booking', verbose_name='الحجز'),
        ),
    ]
