"""
Django settings for hotels project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$&gp2^!(w4%x2zo)1ohk&xk@$10kcw=3w15(t_q(x6$!6gec(p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'HotelManagement.apps.HotelmanagementConfig',  # First because it contains BaseModel
    'users.apps.UsersConfig',
    'rooms.apps.RoomsConfig',
    'bookings.apps.BookingsConfig',
    'reviews.apps.ReviewsConfig',
    'services.apps.ServicesConfig',
    'payments.apps.PaymentsConfig',
    
    # Third party apps
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.AdminTablePermissionsMiddleware',  # إضافة middleware الصلاحيات
]

ROOT_URLCONF = 'hotels.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotels.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hotels-booking',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '54322',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'",
            'charset': 'utf8mb4',
            'use_unicode': True,
            'autocommit': True,
            'isolation_level': 'read committed',
            'sql_mode': 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
        }
    }
}

DATABASE_OPTIONS = {
    'timeout': 20,
    'connect_timeout': 10,
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,  # الحد الأدنى لطول كلمة المرور 4 أحرف
        }
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

# Internationalization settings
LANGUAGE_CODE = 'ar'

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('ar', 'العربية'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# User Model
AUTH_USER_MODEL = 'users.CustomUser'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR , 'static')
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'hotels/static')]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "نظام حجز الفنادق",
    "site_header": "نظام حجز الفنادق",
    "site_brand": "نظام حجز الفنادق",
    "site_logo": "images/logo.png",
    "welcome_sign": "مرحباً بك في نظام حجز الفنادق",
    "copyright": "جميع الحقوق محفوظة",
    "search_model": ["users.CustomUser", "HotelManagement.Hotel"],
    "user_avatar": None,
    
    "topmenu_links": [
        {"name": "الرئيسية", "url": "admin:index"},
        {"name": "الموقع", "url": "home", "new_window": True},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    "order_with_respect_to": [
        "users",
        "users.CustomUser",
        "users.PermissionGroup",
        "users.UserPermission",
        "users.HotelAccountRequest",
        "users.ActivityLog",
        "HotelManagement",
        "HotelManagement.Hotel",
        "HotelManagement.Location",
        "HotelManagement.Phone",
        "HotelManagement.Image",
        "HotelManagement.City",
        "rooms",
        "bookings",
        "reviews",
    ],
    
    "custom_links": {
        "users": [
            {
                "name": "إدارة الصلاحيات", 
                "url": "admin:users_permissiongroup_changelist", 
                "icon": "fas fa-users-cog"
            }
        ],
        "HotelManagement": [
            {
                "name": "إدارة الفنادق",
                "url": "admin:HotelManagement_hotel_changelist",
                "icon": "fas fa-hotel"
            }
        ]
    },
    
    "icons": {
        "users": "fas fa-users",
        "users.CustomUser": "fas fa-user",
        "users.PermissionGroup": "fas fa-users-cog",
        "users.UserPermission": "fas fa-key",
        "users.HotelAccountRequest": "fas fa-user-plus",
        "users.ActivityLog": "fas fa-history",
        "HotelManagement": "fas fa-hotel",
        "HotelManagement.Hotel": "fas fa-building",
        "HotelManagement.Location": "fas fa-map-marker-alt",
        "HotelManagement.Phone": "fas fa-phone",
        "HotelManagement.Image": "fas fa-image",
        "HotelManagement.City": "fas fa-city",
        "rooms.Room": "fas fa-bed",
        "bookings.Booking": "fas fa-calendar-check",
        "reviews.Review": "fas fa-star",
    },
    
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "users.CustomUser": "collapsible",
        "users.PermissionGroup": "horizontal_tabs",
        "users.UserPermission": "horizontal_tabs",
        "auth.group": "collapsible",
        "HotelManagement.Hotel": "horizontal_tabs",
    },
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cyborg",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}
